services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: Tusalvavidas14/foodgram-backend:latest
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
        db:
          condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0:8000 foodgram_backend.wsgi"

  frontend:
    image: Tusalvavidas14/foodgram-frontend:latest
    volumes:
      - frontend_build:/app/build

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
  frontend_build: